# Generated by Django 4.1.3 on 2022-12-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('email', models.CharField(max_length=55)),
                ('uname', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
