# Generated by Django 4.1.3 on 2022-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
