# Generated by Django 4.1.3 on 2022-12-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_users_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=55)),
                ('patient', models.CharField(max_length=55)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
