# Generated by Django 3.0.5 on 2022-12-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_appointments_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
